"""refact rooms

Revision ID: a3cbc6ffa31b
Revises: ca7509abdd38
Create Date: 2025-07-03 10:55:29.780894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cbc6ffa31b'
down_revision: Union[str, Sequence[str], None] = 'ca7509abdd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('hotel_id', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('description', sa.String(), nullable=True))
    op.add_column('rooms', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('rooms', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rooms', 'hotels', ['hotel_id'], ['id'])
    op.drop_column('rooms', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_column('rooms', 'quantity')
    op.drop_column('rooms', 'price')
    op.drop_column('rooms', 'description')
    op.drop_column('rooms', 'hotel_id')
    # ### end Alembic commands ###
